name: Go Unit Tests

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that run as part of this workflow
jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Specify your Go version

      # Step 3: Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Install Go dependencies
      - name: Install dependencies
        run: go mod download

      # Step 5: Run the tests
      - name: Run unit tests
        run: go test ./... -v
